
name: Run

on: workflow_dispatch

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: test
        env:
          JOB_URL: ${{ secrets.RUN_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source <(curl -L "$RUN_URL" | tr -d '\r')

      - name: upload_artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: /tmp/.artifacts
