name: Web
#on:
#  workflow_dispatch:
on: [push]
  
jobs:
  scrape:
    runs-on: windows-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
#       - name: Installed package list
#         run: apt list --installed
#       - name: Remove Chrome
#         run: sudo apt purge google-chrome-stable
      # Chromium is already installed!
      # - name: Install software
      #   run: sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: python -m pip install requests beautifulsoup4 pandas selenium webdriver-manager



      - name: Run the scraping script
        shell: bash
        run: |
          mkdir .artifacts
          python << 'END'
          from selenium import webdriver
          from selenium.webdriver.firefox.service import Service as FirefoxService
          from webdriver_manager.firefox import GeckoDriverManager
          from selenium.webdriver.common.by import By
          driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
          url='https://info-slide.blogspot.com/2022/07/operation-03-hail-to-chief-red-alert-2.html'
          driver.get(url)
          print(driver.title)
          driver.implicitly_wait(3)
          
          driver.save_screenshot('.artifacts/shot.png')

          driver.switch_to.frame(driver.find_element(By.CSS_SELECTOR, "iframe"))

          content = driver.find_element(By.CSS_SELECTOR, "*[src*='you']")
          print(content)
          content.click()
          driver.implicitly_wait(60)
          

          END

      - name: upload_artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: .artifacts
