name: Web
#on:
#  workflow_dispatch:
on: [push]
  
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      # Chromium is already installed!
      # - name: Install software
      #   run: sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: python -m pip install requests beautifulsoup4 pandas selenium webdriver-manager
      - name: Run the scraping script
        run: |
          python << 'END'
          from selenium import webdriver
          from selenium.webdriver.firefox.service import Service as FirefoxService
          from webdriver_manager.firefox import GeckoDriverManager

          driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
          driver.get('http://nytimes.com')
          print(driver.title)
          END

